### PR TITLE
getBoards fix

### PR DESCRIPTION
**Pull request by toreylittlefield**
fixed up the getBoards function assuming it is returning a json object however based on your other get fetch requests I saw in the code I am not certain you're always returning a json object but it is good practice to always return a json object and not a string or other data structure

### CODE REVIEW

**Review by zainafzal88 — CHANGES_REQUESTED** [review]
Thanks for the PR. Although, the code and logic is good, it should've belonged to another method. Please change the code to be in `getBoardNames` method and then we can review this PR again

**Comment by toreylittlefield** [comment]
Changed `getBoards` to `getBoardNames`

**Review by zainafzal88 — CHANGES_REQUESTED** [review]
Thanks for the change @toreylittlefield . Can you please add the code from line 91 to 102 in the existing method (`getBoardNames`). Much appreciated your time and efforts on this

**Comment by toreylittlefield** [comment]
I'll just close this PR and open a new one to avoid the merge conflict

**Pull request closed without merging**
